### ISSUE TITLE
getting errors using Ruby 3.0.1

### ISSUE THREAD

**Issue by ned-pcs** [seattlerb/sexp_processor#31]
I used the `xumlidot` gem to analyze some code and got errors when using Ruby 3.0.1. The same code analyzed fine using Ruby 2.7.2.

The errors looked like this:
```
sexp_processor.rb:221:in `process'

ERROR (#process_class) exp must be a Sexp, was Array:[:module, :CAN_API, s(:call, s(:const, :BusVariable), :new, s(:const, :ID_MEASUREMENT_FW_VERSION), s(:str, "V"), s(:str, "bv_measurement_fw_version"))]

ERROR (#process_class) exp must be a Sexp, was Array:[:module, :TestSupport, s(:call, nil, :include, s(:const, :CAN_API))]
```

**Comment by presidentbeef** [comment]
This is a problem in `xumlidot`.

`Sexp` inherits from `Array`. Previously, some Array methods would return the subclass. E.g. `Sexp#slice` would return an instead of `Sexp`. In Ruby 3.0, this was standardized so all inherited Array methods that return a new Array return an Array instead of the subclass: https://docs.ruby-lang.org/en/3.0.0/NEWS_md.html#label-Core+classes+updates

I've found `Sexp#sexp_body` can replace most uses of `Sexp#slice` or `Sexp#[...]`: https://github.com/seattlerb/sexp_processor/blob/6b7dbc3424ead7c6be572443d8e0cd430ebce500/lib/sexp.rb#L291-L293

**Comment by zenspider** [comment]
Agree with @presidentbeef ... closing
